steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/texas-school-psychology-assistant:lightweight-$COMMIT_SHA",
        ".",
      ]

  # Test the lightweight implementation
  - name: "gcr.io/$PROJECT_ID/texas-school-psychology-assistant:lightweight-$COMMIT_SHA"
    entrypoint: python
    args: ["quick_test.py"]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/texas-school-psychology-assistant:lightweight-$COMMIT_SHA",
      ]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "texas-school-psychology-assistant"
      - "--image"
      - "gcr.io/$PROJECT_ID/texas-school-psychology-assistant:lightweight-$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "1Gi"
      - "--cpu"
      - "1"
      - "--max-instances"
      - "5"
      - "--set-env-vars"
      - "OPENAI_API_KEY=${_OPENAI_API_KEY}"
      - "--set-env-vars"
      - "GCS_USE_STORAGE=${_GCS_USE_STORAGE}"
      - "--set-env-vars"
      - "DEBUG=${_DEBUG}"

images:
  - "gcr.io/$PROJECT_ID/texas-school-psychology-assistant:lightweight-$COMMIT_SHA"

substitutions:
  _OPENAI_API_KEY: "your-openai-api-key-here"
  _GCS_USE_STORAGE: "false"
  _DEBUG: "false"
